---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: nuget
    directory: "Template.App"
    schedule:
      interval: "weekly"
  